Dev/lf
lvafi/testapp2 pull request #1
Opened 2018-09-21 04:24 UTC by lvafi

First PR for code review

2018-09-21 16:35 UTC, deefactorial requested changes
There are a couple of improvements to make on the code.

2018-09-21 16:35 UTC, deefactorial commented on src/app/calculator-component/calculator-component.component.ts
>    }
remove empty ngOnInit

2018-09-21 16:35 UTC, deefactorial commented on src/app/calculator-component/calculator-component.component.ts
> +    // the display needs to be cleared to store the new number
If you need a comment for this put into a function with a descriptive function name instead.

2018-09-21 16:35 UTC, deefactorial commented on src/app/calculator-component/calculator-component.component.ts
> +        */
Do not leave dead code in a comment. remove code or leave a comment of why it's needed in the future.

2018-09-21 16:35 UTC, deefactorial commented on src/app/calculator-component/calculator-component.component.ts
> +    }
move to method

2018-09-21 16:35 UTC, deefactorial commented on src/app/calculator-component/calculator-component.component.ts
> +  }
this method is too long, consider breaking it up into smaller methods, each method should do only one thing.

2018-09-21 16:35 UTC, deefactorial commented on src/app/calculator-component/calculator-component.component.ts
> +    console.log("number is =" + convertedNumber);
remove debugging

2018-09-21 16:35 UTC, deefactorial commented on src/app/calculator.service.spec.ts
> +//import { CalculatorComponentComponent } from './calculator-component/calculator-component.component';
remove unused code.

2018-09-21 16:35 UTC, deefactorial commented on src/app/calculator.service.spec.ts
> +      //CalculatorComponentComponent
remove unused code

2018-09-21 16:35 UTC, deefactorial commented on src/app/calculator.service.ts
> +    console.log("number is =" + tempResult);
remove debugging

2018-09-21 16:35 UTC, deefactorial commented on src/app/calculator.service.ts
> +    // the following logic in production code, will be hidden in the cloud.
Can you explain what hidden in the cloud means ?

2018-09-21 16:35 UTC, deefactorial commented on src/tslint.json
> +        ],
the rules are there for a reason, they are hints on how to improve your code, try returning the rules and fixing the linting errors.

2018-09-21 16:35 UTC, deefactorial commented on src/app/calculator-component/calculator-component.component.html
> +      </div> -->
remove unused code or comment why it's needed.

2018-09-21 16:35 UTC, deefactorial commented on src/app/calculator-component/calculator-component.component.html
> +</div>
Can this component be split into smaller parts ?

2018-09-21 16:35 UTC, deefactorial commented on src/app/calculator-component/calculator-component.component.ts
> +  private operateOnSymbol(op) {
consider moving this logic to the calculator service

2018-09-22 22:05 UTC, lvafi commented
Code review changes in the next PR.

2018-09-22 22:05 UTC, closed without merging